apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriovn6
  name: sriov-dpdk-n6
  namespace: pktgen
spec:
  config: '{ "cniVersion": "0.3.0", "type": "host-device", "device": "eth1" }'
